### ISSUE TITLE
Provisioning and publishing

### ISSUE THREAD

**Issue by steinbro** [openscape-community/openscape#4]
Hi @mikedoise -- I saw from https://github.com/microsoft/soundscape/issues/2#issuecomment-1374918370 that you expressed interest in helping get Soundscape back in the app store. We've made some progress in getting a backend you can stand up yourself (see https://github.com/openscape-community/overscape-server). We still have some work to do in this fork, but if you have an active iOS developer account, I expect that will be of great value to us when we are ready to publish to the app store, and that's what this issue is meant to track.

**Comment by bramd** [comment]
I have a paid developer account and am willing to help out. I never published something myself, my iOS development efforts never left the hobby stage :).

I would prefer to set it up so that multiple people can join in and publish even when I'm not around to do so, I'm not sure if that is possible with a personal dev account.

**Comment by Oliver2213** [comment]
I'm also purchasing a personal dev account (should have it within the next few days) for this org and app; also interested in sharing the build / push to test flight / store capability (I noticed an export button in xcode's account settings, which might be part of that).  
In the longrun, maybe we move towards registering an openscape community business to get a DUNS number or something (so we show up as openscape community as the seller, rather than individual people) after we get something up.

**Comment by bramd** [comment]
I'm in the process of converting my personal account to an organization account, it seems you can't add members to a personal account (or I'm misreading the documentation?). However, my organization is just a personal holding haveing stock in other companies and Apple is complaining that there is no web presence, so I hope I can get this account comverted.

Also, it's not clear to me how easy it would be to transfer the app later to a new account in the name of Openscape Community. Deploying through a personal account where only one person would have access to the required signing profiles and app distribution doesn't feel comfortable to me.

**Comment by Oliver2213** [comment]
If we can distribute under an org named openscape community (or anything other than an individual) that's probably better. I'm looking at purchasing openscape.io for the site (we need a domain for the associated domains capability and beacon sharing anyways); we can make a repo and just use a static site generator or something to build it. Test flight will require a privacy policy at minimum, so that should go there.  
I get not being comfortable with personal distribution - I'm worried its all we have for the moment unless we can get the org with a DUNS number.  
, The app should be pretty easy to transfer among accounts if we need to - change the code signing team for the project.

**Comment by Oliver2213** [comment]
There is [this Apple Developer page](https://developer.apple.com/help/app-store-connect/manage-your-team/add-and-edit-users) that mentions that people you add to a team with a personal dev account do get access to app store connect, so test flight and app store distrobution? hmm. Still not really sure.

**Comment by JessicaTegner** [comment]
publishing can be done with an org account automatically if we get #9  working

**Comment by steinbro** [comment]
I think we have this figured out now with Fastlane.
